id: org.reactome.server.graph.domain.model
name: reactome-data-model
description: Reactome Data Model
prefixes:
  linkml: https://w3id.org/linkml/
  model: org.reactome.server.graph.domain.model
default_prefix: org.reactome.server.graph.domain.model
default_range: string
# version: TBC
imports:
  - linkml:types

# types:
# TBC

subsets:
  web_schema:
    description: >-
      Reactome schema used for the web service
  curator_schema_only:
    description: >-
      Reactome schema used for by the curator tool only
  schema_annotations:
    description: >-
      Annotations used in java classes - external to the schema

classes:

  #### AbstractModifiedResidue ####
  AbstractModifiedResidue:
    is_a: DatabaseObject
    attributes:
      referenceSequence:
        # TODO: ReferenceSequence class
        range: ReferenceSequence
        annotations:
          constraint: MANDATORY
          category: all
          type: "referenceSequence"

  #### Affiliation ####
  Affiliation:
    is_a: DatabaseObject
    attributes:
      address:
        annotations:
          constraint: REQUIRED
      name:
        multivalued: true
        annotations:
          constraint: MANDATORY
          category: all
          addedField: false
    in_subset:
      - curator_schema_only

  #### Anatomy ####
  Anatomy:
    is_a: ExternalOntology
    in_subset:
      - curator_schema_only

  #### BlackBoxEvent ####
  BlackBoxEvent:
    # TODO: ReactionlikeEvent class
    is_a: ReactionlikeEvent
    attributes:
      templateEvent:
        # TODO: Event class
        range: Event
        annotations:
          constraint: OPTIONAL
          type: "templateEvent"
      goBiologicalProcess:
        # TODO: GO_BiologicalProcess class
        range: GO_BiologicalProcess
        annotations:
          constraint: OPTIONAL
          type: "goBiologicalProcess"
      literatureReference:
        multivalued: true
        # TODO: Publication class
        range: Publication
        annotations:
          constraint: REQUIRED
          type: "Publication"
      input:
        # TBC - Note Set instead of List in Java class
        multivalued: true
        # TODO: Input class
        range: Input
        annotations:
          constraint: REQUIRED
          category: all
          type: "input"
      output:
        # TBC - Note Set instead of List in Java class
        multivalued: true
        # TODO: Output class
        range: Output
        annotations:
          constraint: REQUIRED
          category: all
          type: "output"
      catalystActivity:
        multivalued: true
        # TODO: CatalystActivity class
        range: CatalystActivity
        annotations:
          constraint: OPTIONAL
          category: all
          type: "catalystActivity"
      edited:
        mulitvalued: true
        range: InstanceEdit
        annotations:
          constraint: REQUIRED
          type: "edited"
          direction: INCOMING
      authored:
        mulitvalued: true
        range: InstanceEdit
        annotations:
          constraint: REQUIRED
          type: "authored"
          direction: INCOMING
    in_subset:
      - curator_schema_only

  #### ControlledVocabulary ####
  ControlledVocabulary:
    is_a: DatabaseObject
    slots:
      - definition
    attributes:
      name:
        multivalued: true
        annotations:
          constraint: MANDATORY
          addedField: false
    in_subset:
      - curator_schema_only

  #### DatabaseIdentifier ####
  DatabaseIdentifier:
    is_a: DatabaseObject
    attributes:
      identifier:
        # TODO: Confirm - this attribute has to be different from identifier slot because of different annotations
        annotations:
          constraint: MANDATORY
          category: all
          addedField: false
      crossReference:
        multivalued: true
        range: DatabaseIdentifier
        annotations:
          constraint: OPTIONAL
          type: "crossReference"
      referenceDatabase:
        range: ReferenceDatabase
        annotations:
          constraint: MANDATORY
          category: all
          type: "referenceDatabase"
    in_subset:
      - curator_schema_only

  #### DatabaseObject ####
  DatabaseObject:
    attributes:
      isLoaded:
        annotations:
          reactome_transient: true
        range: boolean
      preventLazyLoading:
        range: boolean
        annotations:
          reactome_transient: true
      DB_ID:
        identifier: true
        annotations:
          constraint: NOMANUALEDIT
        readonly: true
      _displayName:
        readonly: true
        annotations:
          addedField: false
      _timestamp:
      created:
        range: InstanceEdit
        annotations:
          constraint: NOMANUALEDIT
          type: "created"
          direction: INCOMING
      modified:
        range: InstanceEdit
        annotations:
          constraint: NOMANUALEDIT
          type: "modified"
          direction: INCOMING
      stableIdentifier:
          annotations:
            constraint: NOMANUALEDIT
            type: "stableIdentifier"
    in_subset:
      - curator_schema_only

  #### _Deleted ####
  _Deleted:
    is_a: DatabaseObject
    attributes:
      curatorComment:
        annotations:
          constraint: NOMANUALEDIT
          addedField: false
      deletedInstanceDB_ID:
        multivalued: true
        range: long
        annotations:
          constraint: NOMANUALEDIT
          addedField: false
      reason:
        range: DeletedControlledVocabulary
        annotations:
          constraint: NOMANUALEDIT
          type: "reason"
      deletedInstance:
        multivalued: true
        range: _DeletedInstance
        annotations:
          constraint: NOMANUALEDIT
          type: "deletedInstance"
      replacementInstances:
        multivalued: true
        range: DatabaseObject
        annotations:
          constraint: NOMANUALEDIT
          type: "replacementInstances"
    in_subset:
      - curator_schema_only

  #### DeletedControlledVocabulary ####
  DeletedControlledVocabulary:
    is_a: ControlledVocabulary
    in_subset:
      - curator_schema_only

  #### _DeletedInstance ####
  _DeletedInstance:
    is_a: DatabaseObject
    attributes:
      deletedInstanceDB_ID:
        multivalued: true
        range: long
        annotations:
          constraint: NOMANUALEDIT
          category: all
          addedField: false
      name:
        annotations:
          constraint: NOMANUALEDIT
          category: all
          addedField: false
      className:
        annotations:
          constraint: NOMANUALEDIT
          addedField: false
      deletedStableIdentifier:
        range: StableIdentifier
        annotations:
          constraint: NOMANUALEDIT
          category: all
          type: "deletedStableIdentifier"
      species:
        multivalued: true
        range: Taxon
        annotations:
          constraint: NOMANUALEDIT
          category: all
          type: "species"
    in_subset:
      - curator_schema_only

  #### ExternalOntology ####
  ExternalOntology:
    is_a: DatabaseObject
    slots:
      - definition
    attributes:
      identifier:
        annotations:
          constraint: MANDATORY
          category: all
          addedField: false
      name:
        multivalued: true
        annotations:
          constraint: MANDATORY
          addedField: false
      synonym:
        multivalued: true
        annotations:
          constraint: OPTIONAL
          addedField: false
      instanceOf:
        multivalued: true
        range: ExternalOntology
        annotations:
          constraint: OPTIONAL
          type: "instanceOf"
      referenceDatabase:
        range: ReferenceDatabase
        annotations:
          constraint: MANDATORY
          type: "referenceDatabase"
    in_subset:
      - curator_schema_only

  #### Figure ####
  Figure:
    is_a: DatabaseObject
    attributes:
      url:
        annotations:
          constraint: MANDATORY
          category: all
          addedField: false
          property: true
    in_subset:
      - curator_schema_only

  #### InstanceEdit ####
  InstanceEdit:
    is_a: DatabaseObject
    attributes:
      dateTime:
        annotations:
          addedField: false
      note:
        annotations:
          addedField: false
      _applyToAllEditedInstances:
        annotations:
          addedField: false
      author:
        multivalued: true
        range: Person
        annotations:
          type: "author"
          direction: INCOMING
    in_subset:
      - curator_schema_only

  #### Person ####
  Person:
    is_a: DatabaseObject
    attributes:
        firstname:
          annotations:
            constraint: OPTIONAL
            category: all
            addedField: false
        initial:
          annotations:
            constraint: MANDATORY
            category: all
            addedField: false
        project:
          annotations:
            constraint: OPTIONAL
            category: all
            addedField: false
        surname:
          annotations:
            constraint: MANDATORY
            category: all
            addedField: false
        url:
          annotations:
            constraint: OPTIONAL
            category: all
            addedField: false
        affiliation:
          multivalued: true
          range: Affiliation
          annotations:
            constraint: OPTIONAL
            type: "affiliation"
        figure:
          multivalued: true
          range: Figure
          annotations:
            constraint: OPTIONAL
            type: "figure"
        crossReference:
          multivalued: true
          range: DatabaseIdentifier
          annotations:
            constraint: OPTIONAL
            type: "crossReference"
    in_subset:
      - curator_schema_only

  #### ReactionlikeEvent ####
  ReactionlikeEvent:
    # TODO: Event class
    is_a: Event
    attributes:
      isChimeric:
        range: boolean
        annotations:
          constraint: OPTIONAL
          addedField: false
      systematicName:
        annotations:
          constraint: OPTIONAL
          addedField: false
      catalystActivity:
        multivalued: true
        # TODO: CatalystActivity class
        range: CatalystActivity
        annotations:
          constraint: REQUIRED
          category: all
          type: "catalystActivity"
      catalystActivityReference:
        # TODO: CatalystActivityReference class
        range: CatalystActivityReference
        annotations:
          constraint: OPTIONAL
          type: "catalystActivityReference"
      entityFunctionalStatus:
        multivalued: true
        # TODO: EntityFunctionalStatus  class
        range: EntityFunctionalStatus
        annotations:
          constraint: OPTIONAL
          category: all
          type: "entityFunctionalStatus"
      entityOnOtherCell:
        multivalued: true
        # TODO: PhysicalEntity class
        range: PhysicalEntity
        annotations:
          constraint: OPTIONAL
          type: "entityOnOtherCell"
      input:
        # TBC - Note Set instead of List in Java class
        multivalued: true
        # TODO: Input class
        range: Input
        annotations:
          constraint: MANDATORY
          category: all
          type: "input"
      output:
        # TBC - Note Set instead of List in Java class
        multivalued: true
        # TODO: Output class
        range: Output
        annotations:
          constraint: MANDATORY
          category: all
          type: "output"
      normalReaction:
        # TODO: ReactionlikeEvent class
        range: ReactionlikeEvent
        annotations:
          constraint: OPTIONAL
          type: "normalReaction"
      regulatedBy:
        multivalued: true
        # TODO: Regulation class
        range: Regulation
        annotations:
          constraint: OPTIONAL
          type: "regulatedBy"
      regulationReference:
        TBC..


  #### ReferenceDatabase ####
  ReferenceDatabase:
    is_a: DatabaseObject
    attributes:
      accessUrl:
        annotations:
          constraint: MANDATORY
          category: any
          addedField: false
      name:
        multivalued: true
        annotations:
          constraint: OPTIONAL
          addedField: false
      url:
        annotations:
          constraint: MANDATORY
          addedField: false
      resourceIdentifier:
        annotations:
          constraint: OPTIONAL
          addedField: false
    in_subset:
      - curator_schema_only

  #### ReferenceSequence ####
  ReferenceSequence:
    is_a: DatabaseObject
    attributes:
      checksum:
        annotations:
          constraint: NOMANUALEDIT
          addedField: false
      comment:
        multivalued: true
        annotations:
          constraint: OPTIONAL
          addedField: false
      description:
        multivalued: true
        annotations:
          constraint: OPTIONAL
          addedField: false
      geneName:
        multivalued: true
        annotations:
          constraint: OPTIONAL
          addedField: false
      isSequenceChanged:
        range: boolean
        annotations:
          constraint: OPTIONAL
          addedField: false
      keyword:
        multivalued: true
        annotations:
          constraint: OPTIONAL
          addedField: false
      secondaryIdentifier:
        multivalued: true
        annotations:
          constraint: OPTIONAL
          addedField: false
      sequenceLength:
        range: integer
        annotations:
          addedField: false
      species:
        range: Species
        annotations:
          constraint: MANDATORY
          category: all
          type: "species"
      otherIdentifier:
        multivalued: true
        annotations:
          constraint: NOMANUALEDIT
          addedField: false
    in_subset:
      - curator_schema_only

  #### Release ####
  Release:
    is_a: DatabaseObject
    attributes:
      releaseNumber:
        range: integer
        annotations:
          constraint: MANDATORY
          addedField: false
      releaseDate:
        annotations:
          constraint: MANDATORY
          addedField: false
    in_subset:
      - curator_schema_only

  #### Species ####
  Species:
    is_a: Taxon
    attributes:
      abbreviation:
        annotations:
          constraint: MANDATORY
          addedField: false

  #### StableIdentifier ####
  StableIdentifier:
    is_a: DatabaseObject
    slots:
      - identifier
      - identifierVersion
    attributes:
      oldIdentifier:
        annotations:
          addedField: false
      oldIdentifierVersion:
        annotations:
          addedField: false
      released:
        range: boolean
        annotations:
          addedField: false
      history:
        multivalued: true
        range: StableIdentifierHistory
        annotations:
          type: "history"
    in_subset:
      - curator_schema_only

  #### StableIdentifierHistory ####
  StableIdentifierHistory:
    is_a: DatabaseObject
    slots:
      - identifier
      - identifierVersion
    attributes:
      historyStatus:
        multivalued: true
        range: StableIdentifierReleaseStatus
        annotations:
          type: "historyStatus"
    in_subset:
      - curator_schema_only

  #### StableIdentifierReleaseStatus ####
  StableIdentifierReleaseStatus:
    is_a: DatabaseObject
    attributes:
      releaseNumber:
        range: integer
        annotations:
          addedField: false
          category: all
      status:
        range: integer
        annotations:
          addedField: false
          category: all
    in_subset:
      - curator_schema_only

  #### Taxon ####
  Taxon:
    is_a: DatabaseObject
    attributes:
      name:
        multivalued: true
        annotations:
          constraint: MANDATORY
          category: any
          addedField: false
      crossReference:
        multivalued: true
        range: DatabaseIdentifier
        annotations:
          deprecated: true
          constraint: MANDATORY
          type: "crossReference"
      superTaxon:
        range: Taxon
        annotations:
          constraint: REQUIRED
          type: "superTaxon"
    in_subset:
      - curator_schema_only

  #### _UpdateTracker ####
  _UpdateTracker:
    is_a: DatabaseObject
    attributes:
      action:
        multivalued: true
        annotations:
          constraint: NOMANUALEDIT
          addedField: false
      _release:
        range: _Release
        annotations:
          constraint: NOMANUALEDIT
          type: "_release"
      updatedInstance:
        multivalued: true
        range: DatabaseObject
        annotations:
          constraint: NOMANUALEDIT
          type: "updatedInstance"
          # TBC: allowed:
          # - Event.class
          # - PhysicalEntity.class
          # did not work
          allowed: "Event.class, PhysicalEntity.class"
    in_subset:
      - curator_schema_only

  #### Annotations classes - start ####
  Annotations:
    attributes:
      reactome_allowed_classes:
        range: ReactomeAllowedClasses
      reactome_transient:
        range: boolean
      reactome_constraint:
        range: ReactomeConstraint
      reactome_property:
        range: ReactomeProperty
      property:
        range: boolean
      relationship:
        range: ReactomeRelationship
      reactome_instance_defining_value:
        range: ReactomeInstanceDefiningValue
      deprecated:
        range: boolean
    in_subset:
      - schema_annotations

  ReactomeAllowedClasses:
    attributes:
      allowed:
        # TBC - note the {} notation in java
        multivalued: true
    in_subset:
      - schema_annotations

  ReactomeConstraint:
    attributes:
      constraint:
        range: ReactomeConstraintValues
    in_subset:
      - schema_annotations

  ReactomeInstanceDefiningValue:
    attributes:
      category: CategoryValues
    in_subset:
      - schema_annotations

  ReactomeProperty:
    attributes:
      addedField:
        range: boolean
    in_subset:
      - schema_annotations

  ReactomeRelationship:
    attributes:
        type:
        direction: RelationshipDirectionValues
    in_subset:
      - schema_annotations
  #### Annotations classes - end ####

#### Enumerations ####
enums:
  ReactomeConstraintValues:
    permissible_values:
      NOMANUALEDIT:
      MANDATORY:
      OPTIONAL:
      REQUIRED:
  RelationshipDirectionValues:
    permissible_values:
      INCOMING:
      OUTGOING:
  ReleaseStatusValues:
    permissible_values:
      EXISTS:
      CREATED:
      INCREMENTED:
      REPLACED:
      ORTHO:
  CategoryValues:
     permissible_values:
       none:
       any:
       all:

#### Enumerations ####
slots:
  identifier:
    annotations:
      addedField: false
  identifierVersion:
    annotations:
      addedField: false
  definition:
    annotations:
      constraint: OPTIONAL
      addedField: False
